u21686875_HW03/Models/ModelFile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace u21686875_HW03.Models
{
    public class ModelFile
    {
        [Display(Name = "File Name")]
        public string FileName { get; set; }

        [Required(ErrorMessage = "Please select file.")]
        [Display(Name = "Browse File")]
        public HttpPostedFileBase[] Files { get; set; }
    }
}

u21686875_HW03/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21686875_HW03.Models;

namespace u21686875_HW03.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            String path = Server.MapPath("~/Content");
            string[] Imagepaths = Directory.GetFiles(path);
            ViewBag.images = Imagepaths;

            return View();
        }
    }
}

u21686875_HW03/Controllers/FileDownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21686875_HW03.Models;

namespace u21686875_HW03.Controllers
{
    public class FileDownloadController : Controller
    {
        // GET: FileDownload
        public ActionResult Index()
        {

            string[] filepaths = Directory.GetFiles(Server.MapPath("~/Media/Documents/"));

            List<ModelFile> files = new List<ModelFile>();

            foreach(string filepath in filepaths)
            {
                files.Add(new ModelFile { FileName = Path.GetFileName(filepath) });
            }
            return View(files);
        }
        public ActionResult DownloadFile(string fileName)
        {

            string path = Server.MapPath("~/Media/Documents/") + fileName;

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            
            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {

            string path = Server.MapPath("~/Media/Documents/") + fileName;

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }

    }
}

u21686875_HW03/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace u21686875_HW03.Controllers
{
    public class FileUploadController : Controller
    {
        // GET: FileUpload
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase files)
        {
            if(files != null && files.ContentLength > 0)
            {
                var fileName = Path.GetFileName(files.FileName);
                var path = Path.Combine(Server.MapPath("~/Media/Documents"), fileName);

                files.SaveAs(path);
            }

            return RedirectToAction("Index");
        }
    }
}

u21686875_HW03/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace u21686875_HW03.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            String path = Server.MapPath("~/Profile/");
            string[] Imagepaths = Directory.GetFiles(path);
            ViewBag.images = Imagepaths;

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

u21686875_HW03/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using u21686875_HW03.Models;
using System.IO;

namespace u21686875_HW03.Controllers
{
    public class ImagesController : Controller
    {
        // GET: Images
        public ActionResult Index()
        {

            string[] Imagepaths = Directory.GetFiles(Server.MapPath("~/Media/Images/"));

            List<ModelFile> images = new List<ModelFile>();

            foreach (string imagepath in Imagepaths)
            {
                images.Add(new ModelFile { FileName = Path.GetFileName(imagepath) });
            }
            return View(images);
        }
        public ActionResult DownloadFile(string fileName)
        {

            string path = Server.MapPath("~/Media/Images/") + fileName;

            byte[] bytes = System.IO.File.ReadAllBytes(path);


            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {

            string path = Server.MapPath("~/Media/Images/") + fileName;

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u21686875_HW03/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21686875_HW03.Models;

namespace u21686875_HW03.Controllers
{
    public class VideosController : Controller
    {
        // GET: Videos
        public ActionResult Index()
        {

            string[] filepaths = Directory.GetFiles(Server.MapPath("~/Media/Videos/"));

            List<ModelFile> files = new List<ModelFile>();

            foreach (string filepath in filepaths)
            {
                files.Add(new ModelFile { FileName = Path.GetFileName(filepath) });
            }
            return View(files);
        }
        public ActionResult DownloadFile(string fileName)
        {

            string path = Server.MapPath("~/Media/Videos/") + fileName;

            byte[] bytes = System.IO.File.ReadAllBytes(path);


            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {

            string path = Server.MapPath("~/Media/Videos/") + fileName;

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u21686875_HW03/Views/About/About.cshtml
@{
    ViewBag.Title = "About";
}

u21686875_HW03/Views/FileDownload/Index.cshtml
@{
    ViewBag.Title = "Index";
}


@using u21686875_HW03.Models
@model List<ModelFile>

<h2>Index</h2>

<style>
    .contain {
        background-color: rgb(221 221 221);
        padding: 30px 30px 30px;
    }
</style>

<h2>Documents of any file type</h2>
<h4>............"Media/Documents/" folder</h4>

<div class="contain">
    <div style="height: 400px; overflow: auto;">
        <div class="well-sm">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">File Name</th>
                        <th scope="col">DOWNLOAD</th>
                        <th scope="col">DELETE</th>
                    </tr>
                </thead>
                @foreach (ModelFile file in Model)
                {
                    <tr>
                        @*
                Default >> @Html.DisplayFor(modelItem => file.FileName)
                        *@

                        <td>@file.FileName</td>
                        <td>
                            <button class="btn btn-success">
                                @Html.ActionLink("Download", "DownloadFile",
                                 new { fileName = file.FileName })
                            </button>
                        </td>
                        <td>
                            <button class="btn btn-danger">
                                @Html.ActionLink("DELETE", "DeleteFile",
                               new { fileName = file.FileName },
                               new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                            </button>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

u21686875_HW03/Views/FileUpload/Images.cshtml
@{
    ViewBag.Title = "Images";
}

<h2>Images of any file type</h2>
<h4>............"Media/Documents/" folder</h4>

<div class="contain">
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <img src="../Views/Home/Assests/Vegeta.jpg" />
                <br />
                <button type="button" class="btn btn-success">Download</button>
                <button type="button" class="btn btn-danger">Delete</button>
            </div>
            <div class="col-sm">
                <img src="../Views/Home/Assests/Vegeta.jpg" />
                <br />
                <button type="button" class="btn btn-success">Download</button>
                <button type="button" class="btn btn-danger">Delete</button>
            </div>
            <div class="col-sm">
                <img src="../Views/Home/Assests/Vegeta.jpg" />
                <br />
                <button type="button" class="btn btn-success">Download</button>
                <button type="button" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </div>
</div>

u21686875_HW03/Views/FileUpload/Index.cshtml
@model IEnumerable<u21686875_HW03.Models.ModelFile>

@{
    ViewBag.Title = "Index";
}

<style>
    .row {
        background-color: rgb(221 221 221);
    }

    .col-sm-4 {
        padding-left: 12px;
    }
</style>

<h2>myMedia</h2>
<h4>Welcome to My Space</h4>

<div>
    <div class="row">
        <h2>Description</h2>
    </div>
    <div class="row">
        @using (Html.BeginForm("Index", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))

        // an encoding type that allows files to be sent through a POST.
        // Quite simply, without this encoding the files cannot be sent through POST.
        {
        <div class="col-sm-7">
            <p>This is a MVC-based project that is coded to upload and download various files</p>
            <p>The following are the kind of files that can be uploaded</p>
            <p>1. Images</p>
            <p>2. Documents</p>
            <p>3. Videos</p>
            <p>All of these are downloadable as well as deletable</p>
        </div>
            <div class="col-sm-3">
                <h2>Option Selection</h2>
                <label>Document</label><input type="radio" value="Document" name="selectedBtn" />
                <br />
                <label>Image</label><input type="radio" value="Image" name="selectedBtn" />
                <br />
                <label>Video</label><input type="radio" value="Video" name="selectedBtn" />
                <br />
                <input type="file" name="files" />
                <br />
                <div><input type="submit" value="Upload" /></div>
            </div>
           
        }
    </div>
    <br />
</div>
<footer>
        <li>@Html.ActionLink("Files Download", "Index", "FileDownload")</li>
    </footer>

u21686875_HW03/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

@using u21686875_HW03.Models
@model List<ModelFile>
<style>
    .row {
        background-color: rgb(221 221 221);
    }

    .col-sm-4 {
        padding-left: 12px;
    }
</style>

<h2>Thabang Kgaladi</h2>
<h4>The Life of a University Student</h4>

<form action="" method="post">
    <div class="container">
        <div class="row">
            <h2>Bio</h2>
        </div>
        <div class="row">

            <div class="col-sm-5">
                <p>The names Thabang Kgaladi, but I'd like to be refered to as Cruzer. '</p>
                <p>I enjoy completing mind boggling tasks or discorvering new things about me, the world and others. This also includes the playing games, creating digital art</p>
                <p>I find watching anime a new source/or drug if you will of television</p>
                <p>I am currently a student at the University of Pretoria studying Information and Knowledge System, in the Software Development stream</p>
                <br />
                <p>Pleased to make you aquintance</p>
            </div>
            <div class="col-sm-4">
                <h2>Thabang Kgaladi</h2>
                @foreach (var images in ViewBag.images)
                {
                     <img src="~/Profile/@Path.GetFileName(images)" width="200" height="300"/>
                }
            </div>
        </div>
    </div>
</form>

u21686875_HW03/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

u21686875_HW03/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<style>
    .row {
        background-color: rgb(221 221 221);
    }

    .col-sm-4 {
        padding-left: 12px;
    }
</style>

<h2>Thabang Kgaladi</h2>
<h4>The Life of a University Student</h4>

<form action="" method="post">
    <div class="container">
        <div class="row">
            <h2>Bio</h2>
        </div>
        <div class="row">

            <div class="col-sm-5">
                <p>The names Thabang Kgaladi, but I'd like to be refered to as Cruzer. '</p>
                <p>I enjoy completing mind boggling tasks or discorvering new things about me, the world and others. This also includes the playing games, creating digital art</p>
                <p>I find watching anime a new source/or drug if you will of television</p>
                <p>I am currently a student at the University of Pretoria studying Information and Knowledge System, in the Software Development stream</p>
                <br />
                <p>Pleased to make you aquintance</p>
            </div>
            <div class="col-sm-4">
                <h2>Thabang Kgaladi</h2>
                <img src="~/Profile/Thabang Kgaladi.jpg" width="200" height="300"/>
            </div>
        </div>
    </div>
</form>

u21686875_HW03/Views/Images/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@using u21686875_HW03.Models
@model List<ModelFile>

<style>
    .contain {
        background-color: rgb(221 221 221);
        padding: 30px 30px 30px;
    }
</style>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<h2>Images of any file type</h2>
<h4>............"Media/Images/" folder</h4>

<div class="contain">
    <div class="card-deck">
        @foreach (var images in Model)
        {
            <div class="card">
                <a href="~/Media/Images/@images.FileName" data-fancybox="gallery">

                    <img src="~/Media/Images/@images.FileName" />
                    <p>@images.FileName</p>
                    <td>
                        <button type="button" class="btn btn-success">@Html.ActionLink("Download", "DownloadFile", new { fileName = images.FileName })</button>
                    </td>

                    <td>
                        <button type="button" class="btn btn-danger">@Html.ActionLink("Delete", "DeleteFile", new { fileName = images.FileName }, new { onclick = "return confirm('Are you sure');" })</button>
                    </td>

                </a>
            </div>

        }
    </div>
</div>

u21686875_HW03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "FileUpload", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Files", "Index", "FileUpload")</li>

                    <li>@Html.ActionLink("Images", "Index", "Images")</li>
                    <li>@Html.ActionLink("Videos", "Index", "Videos")</li>
                    <li>@Html.ActionLink("AboutMe", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
</body>
</html>

u21686875_HW03/Views/Videos/Index.cshtml
@model IEnumerable<u21686875_HW03.Models.ModelFile>

@{
    ViewBag.Title = "Index";
}

<style>
    .contain {
        background-color: rgb(221 221 221);
        padding: 30px 30px 30px;
    }
</style>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<h2>Index</h2>

<h2>Images of any file type</h2>
<h4>............"Media/Videos/" folder</h4>

<div class="contain">
    <div class="container-fluid contain">
        <div class="row">
            <div class="card">
                @foreach (var videos in Model)
                {
                <div class="col-lg-6">
                    <a data-fancybox="gallery" href="~/Media/Videos/@videos.FileName">
                        <video width="320" height="240" controls>
                            <source src="~/Media/Videos/@videos.FileName" type="video/mp4">
                        </video>
                    </a>
                        
                        <p>@videos.FileName</p>
                        <td>
                            <button type="button" class="btn btn-success">@Html.ActionLink("Download", "DownloadFile", new { fileName = videos.FileName })</button>
                        </td>

                        <td>
                            <button type="button" class="btn btn-danger">@Html.ActionLink("Delete", "DeleteFile", new { fileName = videos.FileName }, new { onclick = "return confirm('Are you sure');" })</button>
                        </td>
                </div>
                }
            </div>
        </div>
    </div>
</div>



<script>
    $(document).ready(function () {
        $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });

        $(".zoom").hover(function () {

            $(this).addClass('transition');
        }, function () {

            $(this).removeClass('transition');
        });
    });
</script>